[package]
name = "quakelog-parser"
version = "0.1.0"
edition = "2021"
authors = ["Kelvin César de Andrade <kelvincandrade@gmail.com>"]
rust-version = "1.70"
description = "Quake log parser"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
